In [3]:
# TASK 4.1.1

import numpy as np

# 1. Initialize an empty array with size 2x2
empty_arr = np.empty((2, 2))
print("1. Empty array:\n", empty_arr)

# 2. Initialize an all-one array with size 4x2
ones_arr = np.ones((4, 2) ,dtype=int)
print("\n2. All-one array:\n", ones_arr)

# 3. Array filled with a specific value (shape & type)
filled_arr = np.full((3, 3), fill_value=7, dtype=int)
print("\n3. Full array (3x3 filled with 7):\n", filled_arr)

# 4. Zeros with same shape and type as another array
sample_arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
zeros_like_arr = np.zeros_like(sample_arr)
print("\n4. Zeros like existing array:\n", zeros_like_arr)

# 5. Ones with same shape and type as another array
ones_like_arr = np.ones_like(sample_arr)
print("\n5. Ones like existing array:\n", ones_like_arr)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
numpy_arr = np.array(new_list)
print("\n6. List converted to numpy array:\n", numpy_arr)


1. Empty array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

2. All-one array:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]

3. Full array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like existing array:
 [[0 0 0]
 [0 0 0]]

5. Ones like existing array:
 [[1 1 1]
 [1 1 1]]

6. List converted to numpy array:
 [1 2 3 4]


In [10]:
# TASK 4.1.2

import numpy as np

print("1. Array with values from 10 to 49:")
arr1 = np.arange(10, 50)
print(arr1, "\n")

print("2. 3x3 matrix with values 0 to 8:")
matrix = np.arange(9).reshape(3, 3)
print(matrix, "\n")

print("3. 3x3 identity matrix:")
identity_matrix = np.eye(3)
print(identity_matrix, "\n")

print("4. Random array of size 30 and its mean:")
rand_arr = np.random.random(30)
print(rand_arr)
print("Mean:", rand_arr.mean(), "\n")

print("5. 10x10 random array with min & max values:")
random = np.random.random((10, 10))
print(random)
print("Min:", random.min(), "Max:", random.max(), "\n")

print("6. Zero array of size 10 with 5th element as 1:")
zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr, "\n")

print("7. Reversed array [1,2,0,0,4,0]:")
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr, "\n")

print("8. 2D array with 1 on border and 0 inside (5x5):")
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print(border_arr, "\n")

print("9. 8x8 Checkerboard pattern:")
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2. 3x3 matrix with values 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4. Random array of size 30 and its mean:
[0.15234511 0.34271845 0.31413375 0.83973473 0.17929061 0.8086386
 0.81685877 0.39626609 0.67472013 0.60297461 0.16147363 0.37864578
 0.37817273 0.80941575 0.23614682 0.97359247 0.06901754 0.67474748
 0.55822136 0.30472576 0.2096105  0.29857497 0.12510768 0.14730052
 0.29810247 0.91914582 0.71470304 0.51850963 0.2857791  0.02843524]
Mean: 0.4405703048568435 

5. 10x10 random array with min & max values:
[[0.89489997 0.55218058 0.48915771 0.74826902 0.73442974 0.2525588
  0.28490767 0.36848049 0.42914547 0.91162105]
 [0.73488475 0.80593656 0.51165715 0.20906209 0.26215806 0.78853612
  0.93322295 0.16624029 0.33053067 0.25170445]
 [0.93839333 0.04487816 0.15532995 

In [22]:
# TASK 4.1.3

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print("1. Add the two arrays (x + y):")
print(x + y, "\n")

print("2. Subtract the two arrays (x - y):")
print(x - y, "\n")

print("3. Multiply array x with any integer:")
print(x * 3, "\n")

print("4. Square of each element of array x:")
print(x ** 2, "\n")

print("5. Dot products:")

print("Dot product v · w:")
print(np.dot(v, w))
print()

print("Dot product x · v:")
print(np.dot(x, v))
print()

print("Dot product x · y:")
print(np.dot(x, y))
print()

print("6. Concatenate x and y along rows:")
concat_xy = np.concatenate((x, y), axis=0)
print(concat_xy, "\n")

print("Concatenate v and w along columns:")
concat_vw = np.vstack((v, w))
print(concat_vw, "\n")

print("7. Try to concatenate x and v:")
try:
    result = np.concatenate((x, v), axis=0)
    print(result)
except Exception as e:
    print("Error:", e)
    print("\nExplanation:")
    print("""
    x is a 2×2 matrix (2 rows, 2 columns)
    v is a 1D array with shape (2,)

    When concatenating along rows (axis=0), NumPy expects both arrays
    to have the same number of columns.

    But:
        x has shape (2, 2)
        v has shape (2,) → treated as (2,) not (1,2)

    Because v does NOT have 2 dimensions, NumPy cannot stack it with x directly.
    """)



1. Add the two arrays (x + y):
[[ 6  8]
 [10 13]] 

2. Subtract the two arrays (x - y):
[[-4 -4]
 [-4 -3]] 

3. Multiply array x with any integer:
[[ 3  6]
 [ 9 15]] 

4. Square of each element of array x:
[[ 1  4]
 [ 9 25]] 

5. Dot products:
Dot product v · w:
219

Dot product x · v:
[29 77]

Dot product x · y:
[[19 22]
 [50 58]]

6. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]] 

Concatenate v and w along columns:
[[ 9 10]
 [11 12]] 

7. Try to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation:

    x is a 2×2 matrix (2 rows, 2 columns)
    v is a 1D array with shape (2,)
    
    When concatenating along rows (axis=0), NumPy expects both arrays 
    to have the same number of columns.

    But:
        x has shape (2, 2)
        v has shape (2,) → treated as (2,) not (1,2)

    Because v does NOT have 2 dimensions, NumPy cannot stac

In [19]:
# TASK 4.1.4
# Part 1: Matrices A and B

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A^-1 =\n", np.round(I, 2))

# Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB =\n", AB)
print("BA =\n", BA)

# Prove (AB)ᵀ = Bᵀ * Aᵀ
LHS = AB.T
RHS = np.dot(B.T, A.T)
print("\n\n(AB)^T =\n", LHS)
print("B^T * A^T =\n", RHS)


# Part 2: Solve linear system
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
B_sys = np.array([-1, -3, 9])

# Method 1: Using inverse
X_inv = np.dot(np.linalg.inv(A_sys), B_sys)
print("\nSolution using inverse method [x, y, z] =", np.round(X_inv, 2))

# Method 2: Using np.linalg.solve (more efficient)
X_solve = np.linalg.solve(A_sys, B_sys)
print("Solution using np.linalg.solve [x, y, z] =", np.round(X_solve, 2))


A * A^-1 =
 [[1. 0.]
 [0. 1.]]

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]

Solution using inverse method [x, y, z] = [ 2.  1. -2.]
Solution using np.linalg.solve [x, y, z] = [ 2.  1. -2.]


In [20]:
# TASK 4.2.1

import time
import numpy as np

print("1. ELEMENT-WISE ADDITION")

# Python list addition
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")

# NumPy addition
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds")


print("\n2. ELEMENT-WISE MULTIPLICATION")

# Python list multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")

# NumPy multiplication
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds")


print("\n3. DOT PRODUCT")

# Python list dot product
start = time.time()
dot_py = sum(list1[i] * list2[i] for i in range(1_000_000))
end = time.time()
print("Python List Dot Product Time:", end - start, "seconds")

# NumPy dot product
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy Dot Product Time:", end - start, "seconds")


print("\n4. MATRIX MULTIPLICATION (1000 x 1000)")

# Python list matrix multiplication
matrix1 = [[1]*1000 for _ in range(1000)]
matrix2 = [[1]*1000 for _ in range(1000)]

start = time.time()
result_matrix = [
    [sum(matrix1[i][k] * matrix2[k][j] for k in range(1000))
    for j in range(1000)]
    for i in range(1000)
]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")

# NumPy matrix multiplication
np_matrix1 = np.ones((1000, 1000))
np_matrix2 = np.ones((1000, 1000))

start = time.time()
np_result = np.dot(np_matrix1, np_matrix2)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start, "seconds")


1. ELEMENT-WISE ADDITION
Python List Addition Time: 0.10543680191040039 seconds
NumPy Array Addition Time: 0.004541873931884766 seconds

2. ELEMENT-WISE MULTIPLICATION
Python List Multiplication Time: 0.11046409606933594 seconds
NumPy Array Multiplication Time: 0.005872011184692383 seconds

3. DOT PRODUCT
Python List Dot Product Time: 0.10396122932434082 seconds
NumPy Dot Product Time: 0.0019643306732177734 seconds

4. MATRIX MULTIPLICATION (1000 x 1000)
Python List Matrix Multiplication Time: 120.41159272193909 seconds
NumPy Matrix Multiplication Time: 0.1511843204498291 seconds
